version: '3'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - 80:80
      - 10051:10051
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=azerty
      - MYSQL_DATABASE=zabbix
    depends_on:
      - mysql-server
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
      - 8080:8080
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=azerty
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix-server
    networks:
      - zabbix-network

  mysql-server:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=azerty
      - MYSQL_ROOT_PASSWORD=azerty
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - zabbix-network

networks:
  zabbix-network:
